spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        highlight_sql: true
  config:
    import: application-secret.yml

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql: trace
        orm.jdbc.bind: trace